### ISSUE TITLE
Running Free5gc-populate

### ISSUE THREAD

**Issue by Aharonez** [shynuu/free5gc-populate#2]
Hey, 
Thank you for your contribution!
Have a question about running the go code. After running this:
![image](https://user-images.githubusercontent.com/32020549/185903796-b64a635f-3e4d-45c6-8cc3-c20709903d63.png)

It seems like nothing is happening, should I configure something else?
Note that mongo does run on port 27017:
![image](https://user-images.githubusercontent.com/32020549/185903947-c9318da2-9dfd-4c71-8b14-2c5faa835244.png)

**Comment by shynuu** [comment]
Hi @Aharonez ,
Thanks 👍 

I have modified the README and added some useful information on how to use the tool but basically nothing visible should happen.

You need to check that the tool has properly inserted all the data into the free5gc database and if it's a success, your ueransim's UE should be able to register on the network and establish their PDU sessions.

Keep me posted,

Youssouf

**Comment by Aharonez** [comment]
Hey @shynuu,
Thanks for the quick reply.
mongo is running in a container and I've configured the correct port in the yml file and executed as specify in the updated README, though still don't see new records in the mongo.
Do I still need to list the subscribers via Free5gc GUI maybe?

**Comment by Aharonez** [comment]
took a deeper look and it appears that for some reason the code enters this loop but throwed while executing its content (I putted a print outside of the loop and compiled but never got there)
![image](https://user-images.githubusercontent.com/32020549/188562108-85f71423-ded3-4b34-b8d0-6c9bbecc3c66.png)

**Comment by Aharonez** [comment]
Solved after properly configuring mongo port and slices. Sorry @shynuu and thanks for your time.
Closing this issue - just one question, we still need to create a uecfg file for each UE to run it in ueransim, right? meaning if I create 100,000 UEs - must create also 100,000 files to be executed in ueransim for the PDU session?

**Comment by shynuu** [comment]
No problem @Aharonez.

For UERANSIM, it depends if you are executing 100 000 instances of `nr-ue` or if you are using the feature provided here: https://github.com/aligungr/UERANSIM/wiki/Usage#basic-usage

In the latter case, you will only have to create a single config.yaml file and the IMSI will be generated automatically by UERANSIM alongside the associated PDU Session.

Youssouf
